@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0
hide circle

class CommandRunner LOGIC_COLOR {
  - isRunning: boolean
  + run(cmd: ParsedCommand): void
}

class TaskCommandHandler LOGIC_COLOR_T1 {
  - skuList: SKUList
  + handleAddSkuTask(cmd: ParsedCommand): void
  + handleDeleteTask(cmd: ParsedCommand): void
  + handleEditTask(cmd: ParsedCommand): void
  + handleMarkTask(cmd: ParsedCommand): void
  + handleUnmarkTask(cmd: ParsedCommand): void
}

class SKUList MODEL_COLOR {
}

class SKU MODEL_COLOR_T1 {
  - skuID: String
  - skuLocation: Location
  - skuTaskList: SKUTaskList
}

class SKUTaskList MODEL_COLOR_T2 {
  - skuTaskList: ArrayList<SKUTask>
  + addSKUTask(skuID: String, priority: Priority, dueDate: String, desc: String): void
  + deleteSKUTaskByIndex(index: int): void
  + editSKUTask(index: int, newDate: String, newPriority: Priority, newDesc: String): void
  + getSKUTaskList(): ArrayList<SKUTask>
  + markTask(taskIndex: int): void
  + unmarkTask(taskIndex: int): void
}

class SKUTask MODEL_COLOR_T3 {
  - skuTaskID: String
  - priority: Priority
  - dueDate: String
  - isDone: boolean
  - taskDescription: String
  + mark(): void
  + unmark(): void
  + isDone(): boolean
}

CommandRunner -down-> TaskCommandHandler : delegates to
TaskCommandHandler -down-> "1" SKUList : skuList
SKUList -down-> "*" SKU : skuList
SKU -down-> "1" SKUTaskList : skuTaskList
SKUTaskList -down-> "*" SKUTask : skuTaskList
@enduml
