@startuml
!include ../style.puml
skinparam arrowThickness 1.1

class CommandRunner LOGIC_COLOR {
  - isRunning: boolean
  + handleAddSkuTask(cmd: ParsedCommand): void
  + handleDeleteTask(cmd: ParsedCommand): void
  + handleEditTask(cmd: ParsedCommand): void
  + handleListTasks(cmd: ParsedCommand): void
}

class SKUList MODEL_COLOR {
}

class SKU MODEL_COLOR_T1 {
  - skuID: String
  - skuLocation: Location
}

class SKUTaskList MODEL_COLOR_T2 {
  + addSKUTask(skuID: String, priority: Priority, dueDate: String, desc: String): void
  + deleteSKUTaskByIndex(index: int): void
  + editSKUTask(index: int, newDate: String, newPriority: Priority, newDesc: String): void
}

class SKUTask MODEL_COLOR_T3 {
  - skuTaskID: String
  - priority: Priority
  - dueDate: String
  - isDone: boolean
  - taskDescription: String
}

CommandRunner -down-> "1" SKUList : skuList
SKUList -down-> "*" SKU : skuList
SKU -down-> "1" SKUTaskList : skuTaskList
SKUTaskList -down-> "*" SKUTask : skuTaskList
@enduml
