@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0
hide circle

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title System Memory State (Steps 1 to 3)

class "cmd:ParsedCommand" as cmd {
    commandWord = "addsku"
    args = {"n": "PALLET-A", "l": "A1"}
}

class "skuHandler:SKUCommandHandler" as handler

class "skuList:SKUList" as skuList {
    skuList = []
}

handler -right-> cmd : reads properties from >
handler -down-> skuList : searches for duplicates in >

@enduml