@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam classAttributeIconSize 0
hide circle

title System Memory State (Step 5)

class "<u>skuList:SKUList</u>" as skuList

class "<u>sku:SKU</u>" as sku {
    skuID = "PALLET-A"
    skuLocation = Location.A1
}

class "<u>skuTaskList:SKUTaskList</u>" as taskList

skuList --> sku : contains >
sku --> taskList : owns and encapsulates >

@enduml