' UI Component (Greens)
!define UI_COLOR #1D8900
!define UI_COLOR_T1 #83E769
!define UI_COLOR_T2 #3FC71B
!define UI_COLOR_T3 #166800
!define UI_COLOR_T4 #0E4100

' Logic Component (Blues)
!define LOGIC_COLOR #3333C4
!define LOGIC_COLOR_T1 #C8C8FA
!define LOGIC_COLOR_T2 #8A8AFA
!define LOGIC_COLOR_T3 #2121BD
!define LOGIC_COLOR_T4 #101086

' Model Component (Reds)
!define MODEL_COLOR #9D0012
!define MODEL_COLOR_T1 #FFA6A6
!define MODEL_COLOR_T2 #FF5959
!define MODEL_COLOR_T3 #8B0010
!define MODEL_COLOR_T4 #72000D

' Storage Component (Yellows/Browns)
!define STORAGE_COLOR #A38300
!define STORAGE_COLOR_T1 #FFE26B
!define STORAGE_COLOR_T2 #FFD521
!define STORAGE_COLOR_T3 #806600
!define STORAGE_COLOR_T4 #5C4A00

' Common/Utility Classes (Grays)
!define USER_COLOR #000000
!define COMMON_COLOR #808080