@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant ":CommandRunner" as runner LOGIC_COLOR
Participant ":SKUList" as skuList MODEL_COLOR
Participant ":SKU" as sku MODEL_COLOR_T1
Participant ":SKUTaskList" as taskList MODEL_COLOR_T2
Participant ":SKUTask" as task MODEL_COLOR_T3

user -> ui ++ : "unmarktask n/P-A i/1"
ui -> parser ++ : parse(...)
return cmd : ParsedCommand

ui -> runner ++ : run(cmd)
runner -> runner ++ : handleUnmarkTask(cmd)

runner -> runner ++ : findSku("P-A")
runner -> skuList ++ : getSKUList()
return List<SKU>
return targetSku

runner -> sku ++ : getSKUTaskList()
return taskList

runner -> taskList ++ : getSKUTaskList()
return ArrayList<SKUTask>

runner -> task ++ : isDone()
return true

runner -> taskList ++ : unmarkTask(1)
taskList -> task ++ : unmark()
return
return

return
return
return display success message
@enduml
