@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant ":CommandRunner" as runner LOGIC_COLOR
Participant ":TaskCommandHandler" as taskHandler LOGIC_COLOR_T2
Participant ":SKUList" as skuList MODEL_COLOR
Participant ":SKU" as sku MODEL_COLOR_T1
Participant ":SKUTaskList" as taskList MODEL_COLOR_T2

user -> ui ++ : "deletetask n/P-A i/1"
ui -> parser ++ : parse(...)
return cmd : ParsedCommand

ui -> runner ++ : run(cmd)
runner -> taskHandler ++ : handleDeleteTask(cmd)

taskHandler -> skuList ++ : findByID("P-A")
return targetSku

taskHandler -> sku ++ : getSKUTaskList()
return taskList

taskHandler -> taskList ++ : deleteSKUTaskByIndex(1)
taskList -> taskList ++ : skuTaskList.remove(0)
return
return

return
return
return display success message
@enduml
