@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant ":CommandRunner" as runner LOGIC_COLOR
Participant ":ViewCommandHandler" as viewHandler LOGIC_COLOR_T2
Participant "<<class>>\nCommandHelper" as CommandHelper LOGIC_COLOR_T3
Participant ":SKUList" as skuList MODEL_COLOR
Participant ":SKU" as sku MODEL_COLOR_T1
Participant ":SKUTaskList" as taskList MODEL_COLOR_T2
Participant ":SKUTask" as task MODEL_COLOR_T3

user -> ui ++ : "listtasks n/P-A"
ui -> parser ++ : parse(...)
return cmd : ParsedCommand

ui -> runner ++ : run(cmd)
runner -> viewHandler ++ : handleListTasks(cmd)

viewHandler -> CommandHelper ++ : findSkuOrError(skuList, "P-A")
CommandHelper -> skuList ++ : findByID("P-A")
return targetSku
return targetSku

viewHandler -> sku ++ : getSKUTaskList()
return taskList

viewHandler -> taskList ++ : getSKUTaskList()
return ArrayList<SKUTask>

loop for each printed task
    viewHandler -> task ++ : toString()
    task -> task ++ : isDone()
    return isDone
    task -> task ++ : getSKUTaskID()
    return id
    task -> task ++ : getSKUTaskPriority()
    return priority
    task -> task ++ : getSKUTaskDueDate()
    return dueDate
    return formattedString
end

return
return
return display tasks
@enduml
