@startuml
!include ../style.puml
skinparam arrowThickness 1.1

class storageSystem STORAGE_COLOR {
    - {static} FILE_PATH : String
    + {static} saveState(skuList : SKUList, taskMap : HashMap) : void
    + {static} loadState(skuList : SKUList, taskMap : HashMap) : void
}

class SKUList MODEL_COLOR {
    + getSKUList() : List
    + addSKU(skuID : String, skuLocation : Location) : void
}

class SKUTaskList MODEL_COLOR_T2 {
}

storageSystem -down-> "1" SKUList : skuList
storageSystem -down-> "*" SKUTaskList : taskMap
@enduml