@startuml
!include ../style.puml

Actor User as user USER_COLOR
Participant ":Ui" as ui UI_COLOR
Participant ":ItemTasker" as main UI_COLOR_T1
Participant ":Parser" as parser LOGIC_COLOR_T1
Participant "runner:CommandRunner" as runner LOGIC_COLOR
Participant "viewHandler:ViewCommandHandler" as handler LOGIC_COLOR_T2
Participant "viewer:ViewSKUTask" as viewer LOGIC_COLOR_T3
Participant "skuList:SKUList" as skuList MODEL_COLOR
Participant "parentSku:SKU" as sku MODEL_COLOR_T1
Participant "tasks:SKUTaskList" as taskList MODEL_COLOR_T2

user -> ui : "listtasks n/A123"
activate ui
ui -> main : readInput()
activate main

main -> parser : parse(input)
activate parser
return cmd

main -> runner : run(cmd)
activate runner

runner -> handler : handleListTasks(cmd)
activate handler

create viewer
handler -> viewer : ViewSKUTask()

handler -> viewer : setSkuFilter("A123")
activate viewer
return

handler -> viewer : listTasks(skuList)
activate viewer

viewer -> skuList : getSKUList()
activate skuList
return List<SKU>

loop for each parentSku in List
    viewer -> sku : getSKUTaskList()
    activate sku
    return taskList

    viewer -> taskList : getSKUTaskList()
    activate taskList
    return List<SKUTask>
end

note right of viewer : viewer filters the list by \nSKUTaskID internally
return results:List<SKUTask>

handler -> ui : printTasksForSku("A123", results)
activate ui
ui --> user : display results
return

return
return
return
deactivate main
@enduml