@startuml
!include ../style.puml
skinparam arrowThickness 1.1

class CommandRunner LOGIC_COLOR {
  - isRunning: boolean
  + handleAddSku(cmd: ParsedCommand): void
}

class SKUList MODEL_COLOR {
  + addSKU(skuID: String, skuLocation: Location): void
}

class "HashMap<String, SKUTaskList>" as taskMap MODEL_COLOR_T2

class SKU MODEL_COLOR_T1 {
  - skuID: String
  - skuLocation: Location
}

class SKUTaskList MODEL_COLOR_T1 {
}

CommandRunner -down-> "1" SKUList : skuList
CommandRunner -down-> "1" taskMap : taskMap
SKUList -down-> "*" SKU : skuList
taskMap -down-> "*" SKUTaskList : values
@enduml